version: '2'
services:
  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    image: flask-test
    depends_on:
      - app
    command: bash -c "chmod +x test.sh && ./test.sh"
    
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: flask-app
    ports:
    - "5000:5000"
       